apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kontox-secret-spc
  namespace: main-api
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "Kontox-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db-username
          - path: password
            objectAlias: db-password
  secretObjects:
    - secretName: kontox-secret-k8s
      type: Opaque
      data:
        - objectName: db-username
          key: username
        - objectName: db-password
          key: password
